MethodCalledOnDoEndBlock:
  Enabled: true

HashSyntax:
  Enabled: false

LineLength:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SymbolArray:
  Enabled: true

TrailingBlankLines:
  Enabled: false

TrailingWhitespace:
  Enabled: false