Style/LineLength:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true