MethodCalledOnDoEndBlock:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingWhitespace:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SymbolArray:
  Enabled: true